### ISSUE TITLE
2.2 Release has a broken signature

### ISSUE THREAD

**Issue by trullock** [optimizely/csharp-sdk#108]
I get this at runtime with the latest 2.2 release

> Could not load file or assembly 'OptimizelySDK' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by mikeng13** [comment]
Thanks for reporting. This is now fixed in: https://github.com/optimizely/csharp-sdk/releases/tag/v2.2.1
