### ISSUE TITLE
HttpClientEventDispatcher45 should allow HttpClient injection

### ISSUE THREAD

**Issue by martincostello** [optimizely/csharp-sdk#145]
As a consequence of #33, the `HttpClientEventDispatcher45` class has a singleton `HttpClient` instance that is used for all requests.

For ASP.NET Core 2.2+ applications, this works against the benefits added by new abstractions such as [`IHttpClientFactory`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2) which handles things like connection pooling and honouring DNS TTL values.

If the .NET Standard versions of the SDK added a constructor overload that allowed an `HttpClient` instance to be provided by the consuming application, such applications could customise the event dispatcher to leverage their own built-in IoC for `HttpClient`, which would then also leverage any custom `HttpMessageHandler` instances, such as for logging and monitoring etc.

At present the only way for the integrator to achieve such benefits is to implement a custom `IEventDispatcher` which is 99% copy-pasted code from the SDK itself.

**Comment by alexsaves** [comment]
Thanks for this feedback @martincostello. I'm going to loop in some members of the team on this and get back to you.

**Comment by alexsaves** [comment]
We've accepted this suggestion and will work this into our backlog - hopefully for next sprint.

**Comment by JosephWoodward** [comment]
@alexsaves Any news on this?

**Comment by mikechu-optimizely** [comment]
We have a mid-2023 goal of updating this SDK to better handle pooled `HttpClient` usage (for ref work item FSSDK-8663 created 20 Oct) 

Alongside side that effort, we're looking to update the version .NET in use.

Thanks for the analysis.

**Comment by mikechu-optimizely** [comment]
I've added a link to this Issue into the Jira.
