### ISSUE TITLE
Is this supported with Xamarin?

### ISSUE THREAD

**Issue by assanesuzy** [optimizely/csharp-sdk#261]
I was trying to compile with this packages and I saw that there is a sdependency that Xamarin does not use which is the System.Confugration.ConfigurationManager. Should this be added in order to use this package for Xamarin? Or do we have to create bindings for the native packages?

**Comment by msohailhussain** [comment]
Thanks for pointing out this issue. It's been fixed and released in 3.9.0 version.

**Comment by assanesuzy** [comment]
Can you link the release notes please? I do not see any reference to xamarin other than using the C# packcage which is already not recommended for mobile.

**Comment by assanesuzy** [comment]
@msohailhussain bump
