### ISSUE TITLE
Please clarify code documentation to indicate methods which should not be used for new projects

### ISSUE THREAD

**Issue by mhenry-cb** [optimizely/csharp-sdk#290]
Please clarify XML doc comments and/or add Obsolete attributes to indicate methods which should not be used for new projects.

For example, `Optimizely.Activate` should not be used with a "Flags project which uses the new SDK".

The following docs appear to need updating as well:
- README
- docs under docs/readme-sync/sdk-reference-guides/csharp-sdk

**Comment by dustin-sier** [comment]
Thanks for the information, we'll be discussing our options for documenting this.

**Comment by dustin-sier** [comment]
We've added a set of stories to our backlog to address this across SDKs. We won't be using the Obsolete attribute because these code paths are still supported, but just not with the new project format.
