### ISSUE TITLE
IOptimizely doesnt have GetFeatureVariableJSON

### ISSUE THREAD

**Issue by ShubhamGargCTH** [optimizely/csharp-sdk#302]
GetFeatureVariableJSON is available in Optimizely it would be nice to have this as part of IOptimizely interface. So that we can mock implementation of Optimizely in our unit test cases.

**Comment by mikechu-optimizely** [comment]
Hi @ShubhamGargCTH ,

I'm working on addressing GitHub Issues. Sorry about the delay.   

Did you find a way to unit test?  (reflection perhaps)?

Thanks for an update.

Mike

**Comment by mikechu-optimizely** [comment]
Looks like this Issue is similar to  #316.

I've created a work item (FSSDK-8701) for us to fold into our sprint planning.

**Comment by mikechu-optimizely** [comment]
Both this and #316 are still in our active backlog. Thanks for hanging in there.

**Comment by russell-loube-optimizely** [comment]
Hi @ShubhamGargCTH , we have merged required changes for this issue (https://github.com/optimizely/csharp-sdk/pull/353). However, we will not be performing a formal release immediately as we are in beta for new functionality.

These changes will be included in our next release once we exit beta for the aforementioned new features. If any questions or concerns, please let us know. Thank you.
