### ISSUE TITLE
IOptimizely - implementation of Get functions incomplete

### ISSUE THREAD

**Issue by edegagneOptimizely** [optimizely/csharp-sdk#316]
Some functions are not implemented in the interface, are there plans to fix this?

Example: GetConfiguration().

If I use DI, I can't make that call unless I use Optimizely object directly.

**Comment by mikechu-optimizely** [comment]
Hi @edegagneOptimizely @simone-coelho has asked us to begin looking into the history of `GetConfiguration` to find out why it's not part of the interface.

**Comment by mikechu-optimizely** [comment]
@msohailhussain will be my first stop after reviewing commit history.

**Comment by mikechu-optimizely** [comment]
Hi @edegagneOptimizely,

It looks like we intentionally require the public facing methods to be called off our concrete implementation. 

Can you give us more context on what you are attempting?

**Comment by edegagneOptimizely** [comment]
Dependency injection through the interface and not the concrete implementation.

Ed DeGagne
Enterprise Cloud Architect

Mobile: +1 978.877.6083
Email: ***@***.******@***.***>
Web: www.optimizely.com<https://www.optimizely.com/>

***@***.***
***@***.***<https://www.linkedin.com/company/optimizely>   ***@***.*** <https://www.facebook.com/optimizely>    ***@***.*** <https://twitter.com/optimizely>    ***@***.*** <https://www.instagram.com/optimizely/>

**Comment by mikechu-optimizely** [comment]
Looks like you and Issue #302 are after the same thing.

I've created a new Jira item (FSSDK-8701) for this and we'll add it to our work pipeline after pointing.

**Comment by russell-loube-optimizely** [comment]
Hey @edegagneOptimizely , see https://github.com/optimizely/csharp-sdk/pull/353 for changes to address this. We will include this in our next release once we exit beta for Advanced Audience Targeting.
