### ISSUE TITLE
HttpClientEventDispatcher45 creates a new HttpClient for every request

### ISSUE THREAD

**Issue by ryandle** [optimizely/csharp-sdk#33]
HttpClientEventDispatcher45 creates a new HttpClient for every request, which goes against the usage guidance for this class. Doing this will cause socket exhaustion under heavy load.

From the [.NET framework docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7):

>HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.

**Comment by kellyroach-optimizely** [comment]
Issue #33 should be resolved by P.R. #36 checked into master branch
https://github.com/optimizely/csharp-sdk/pull/36
https://github.com/optimizely/csharp-sdk/commit/dc40c801fef3cb9d68d1a80179f06caf3c97d09e
Expect this fix to appear in a future release off master branch.
