### ISSUE TITLE
Last-Modified format is invalid

### ISSUE THREAD

**Issue by nuttytree** [optimizely/csharp-sdk#360]
After updating to version 3.11.3 from 3.11.2.1 (which added reading the Last-Modified header) we get error `The format of value '05/18/2023 13:35:06 +00:00'` is invalid and cannot get the latest configuration.

**Comment by mikechu-optimizely** [comment]
Grrrr I can't believe I didn't wrap a proper test around the [proper format of `If-Modified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since). Sounds like I also need e2e tests in there too. 

I'm getting my PM to create a bug ticket.

**Comment by mikechu-optimizely** [comment]
@nuttytree Would you mind taking a quick review of the above whenever you have a chance?  Thanks! 👍

**Comment by nuttytree** [comment]
Without digging to far into how that date is handled downstream it looks good.  Only question is should it be stored as a string and converted back and forth between a DateTime and a string or just stored as a DateTime (keep in mind I have not dug into the code enough to see if there is maybe an obvious reason it should be this way)?

**Comment by mikechu-optimizely** [comment]
Merged to `master`. I have 1 more bug fix before creating a patch release 3.11.4.

**Comment by mikechu-optimizely** [comment]
Released 3.11.4 to NuGet.

Thanks for the help on this one.
