### ISSUE TITLE
Timing issue with Activate() & Track() being called sequentially while not able to await on the async method calls

### ISSUE THREAD

**Issue by HistoricallyCorrect** [optimizely/csharp-sdk#51]
I hit a bug with Optimizely C# SDK when toying in "short lived" console app. The issue is mainly that the SDK does not employ C# async/await best practice "**Async All the Way**". Reference can be [here](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx).

The problematic code is [here](https://github.com/optimizely/csharp-sdk/blob/dc40c801fef3cb9d68d1a80179f06caf3c97d09e/OptimizelySDK/Event/Dispatcher/HttpClientEventDispatcher45.cs#L77) and the usages are [here](https://github.com/optimizely/csharp-sdk/search?utf8=%E2%9C%93&q=EventDispatcher.DispatchEvent&type=). And the two scenarios that I came up with are as below:

```C#
//Scenario 1
var client = new Optimizely(dataFile);
client.Activate("experimentId", "userId", attrs);
//Activate() will call SendImpressionEvent() which calls EventDispatcher.DispatchEvent(impressionEvent); But Activate() does not have an async method signature, hence not possible to await on the response.

client.Track("Clicks", "userId");
//By the time Track() is called, if above DispatchEvent is still in-flight (not complete), I'm assuming Track() will fail due to "userId" has not been activated for "experimentId".

```

```C#
//Scenario 2
var client = new Optimizely(dataFile);
client.Activate("experimentId", "userId", attrs);
client.Track("Clicks", "userId");
//At this point in time, my console app exits, because Track() does not have an async method signature, hence I'm not able to tell if the DispatchEvent inside Track() has completed successfully ot not.
```

I'll also submit a PR for fix soon.

**Update**:

Having had a bit more time to think about this issue, I believe it is best for DispatchEvent() to be sequential and not fire & forget. For fire & forget, it is best to be more explicit in terms of method signature.

Proposed change is here:

https://github.com/HistoricallyCorrect/csharp-sdk/commit/44ffbbfd2598bcd9a60d678b88d1e667d1865eab

**Comment by HistoricallyCorrect** [comment]
@mikeng13

**Comment by kellyroach-optimizely** [comment]
Thank you for submitting your issue, the care with which you wrote it, and the suggested code change which you believe would resolve the issue.  We will take a careful look at what you've written.  I've included all the information you've supplied in an internal Optimizely JIRA ticket which we will study and follow up on.

**Comment by HistoricallyCorrect** [comment]
@kellyroach-optimizely do you have an ETA in terms of when a change would be made to address the reported issue?

**Comment by kellyroach-optimizely** [comment]
I'm convinced there is merit in your proposal, but it will go through normal process,
and I can't ETA or promise on the behalf of Optimizely.

**Comment by HistoricallyCorrect** [comment]
There are 3 PRs for this single issue. Are any one of them ready to be merged yet? Thanks.

**Comment by kellyroach-optimizely** [comment]
P.R. #54 ADDRESSING ISSUE #51 HAS BEEN APPROVED AND MERGED
The competing P.R. #52 and P.R. #53 which now propose identical code changes
were considered. We think P.R. #54 is the best proposal and it has been APPROVED
and MERGED.
https://github.com/optimizely/csharp-sdk/pull/54

**Comment by HistoricallyCorrect** [comment]
Thanks.

Now awaiting on the latest nuget package.

Cheers.

**Comment by mikeng13** [comment]
Going to close this as it is now obsolete.
