### ISSUE TITLE
JsonNet.PrivateSettersContractResolvers.Source dependency is leaky. 

### ISSUE THREAD

**Issue by jwellman-uship** [optimizely/csharp-sdk#78]
Consider pulling this source directly into the project or relying on a dll instead if one is available.  Since the source is being pulled in that will pull this source into any project that relies on the Optimizely nuget anywhere down stream.

**Comment by artempushkin** [comment]
+1. The source file conflicts with our code validation rules.

**Comment by mikeng13** [comment]
Thanks for reporting. This is now fixed in https://github.com/optimizely/csharp-sdk/releases/tag/v2.2.1
