### ISSUE TITLE
EventTagUtils.GetNumericValue() incorrectly logs an error when no value key is present

### ISSUE THREAD

**Issue by jwilke** [optimizely/csharp-sdk#85]
My organization is in the process of upgrading clients and have started seeing this error:

> The numeric metric key is not in event tags.

After some investigation, we have traced it down to this function call
https://github.com/optimizely/csharp-sdk/blob/466feefdb46517d7a94d2d4475921a583bda4cf8/OptimizelySDK/Event/Builder/EventBuilder.cs#L219

Contrast EventTagUtils.GetNumericValue() to EventTagUtils.GetRevenueValue(). Notice that when the revenue key is not present in the event tags, it logs as a debug.  I assume the same pattern should be applied to GetNumericValue()

My organization is working around this by simply adding "value":0, to our event tags for now since error level logs will cause issues in our production system.

**Comment by mikeng13** [comment]
Thanks! We will look into this.

**Comment by mikeng13** [comment]
This should be fixed as of: https://github.com/optimizely/csharp-sdk/releases/tag/v2.2.1
